M48
; DRILL file {KiCad 7.0.1} date Fri Mar 31 16:59:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-31T16:59:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X2.2944Y-1.9745
X2.2944Y-2.1655
T2
X2.1751Y-1.9627
X2.1751Y-2.1773
T0
M30
